language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
  - 7.2
  - 7.2snapshot
  - master
install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit
